name: .NET CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'SEMS.API/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'SEMS.API/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./SEMS.API

    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./SEMS.API